### PR TITLE
Remove filter by tags from main page

### PR DESCRIPTION
**Pull request by bev-a-tron**
Remove filter by tags from main page.  (Did you say there was another change to make?  Let me know if I'm missing something!)

### CODE REVIEW

**Comment by bucchere** [comment]
Looks good. Please also remove it from the statement/show page, e.g. http://fixdemocracyfirst.us/statements/19-dylan-ratigan-a-bought-government

**Comment by bev-a-tron** [comment]
OH!  That's what you meant!  Got it!

**Comment by bev-a-tron** [comment]
(In Jed-Bartlet-voice) What's next?

**Comment by bucchere** [comment]
Thanks, Beverly! Next, I'd like to create a "carousel" that will feature up to N videos on the home page with a distinct treatment from the standard grid of videos. I'll open a git issue with some design suggestions.

**Pull request merged**
